### ISSUE TITLE
null safety version

### ISSUE THREAD

**Issue by ziasultan2** [masashi-sutou/flutter_ios_voip_kit#41]
Please upgrade it to support null safety

**Comment by hovanhung98hust** [comment]
same issue

**Comment by WillowWisp** [comment]
I opened a PR to migrate to Flutter 2. While waiting for the review, you can use my forked repository:

```yaml
dependencies:
  flutter_ios_voip_kit:
    git:
      url: https://github.com/WillowWisp/flutter_ios_voip_kit.git
```
